### PR TITLE
Respect strict/non-strict MySQL modes

### LINKED ISSUE #17: Support disabling `STRICT_TRANS_TABLES` and `STRICT_ALL_TABLES`
When neither of `STRICT_TRANS_TABLES` and `STRICT_ALL_TABLES` SQL modes is set, MySQL applies [implicit default values](https://dev.mysql.com/doc/refman/8.4/en/data-type-defaults.html#data-type-defaults-implicit) in insert and update statements in the following way:

> If a data type specification includes no explicit DEFAULT value, MySQL determines the default value as follows:
>
> If the column can take NULL as a value, the column is defined with an explicit DEFAULT NULL clause.
>
> If the column cannot take NULL as a value, MySQL defines the column with no explicit DEFAULT clause.
>
> For data entry into a NOT NULL column that has no explicit DEFAULT clause, **if an [INSERT](https://dev.mysql.com/doc/refman/8.4/en/insert.html) or [REPLACE](https://dev.mysql.com/doc/refman/8.4/en/replace.html) statement includes no value for the column, or an [UPDATE](https://dev.mysql.com/doc/refman/8.4/en/update.html) statement sets the column to NULL**, MySQL handles the column according to the SQL mode in effect at the time:
>
> - If strict SQL mode is enabled, an error occurs for transactional tables and the statement is rolled back. For nontransactional tables, an error occurs, but if this happens for the second or subsequent row of a multiple-row statement, the preceding rows are inserted.
>
> - If strict mode is not enabled, MySQL sets the column to the implicit default value for the column data type.

Implicit defaults are defined as follows:

> - For numeric types, the default is 0, with the exception that for integer or floating-point types declared with the AUTO_INCREMENT attribute, the default is the next value in the sequence.
> - For date and time types other than [TIMESTAMP](https://dev.mysql.com/doc/refman/8.4/en/datetime.html), the default is the appropriate “zero” value for the type. This is also true for [TIMESTAMP](https://dev.mysql.com/doc/refman/8.4/en/datetime.html) if the [explicit_defaults_for_timestamp](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp) system variable is enabled (see [Section 7.1.8, “Server System Variables”](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html)). Otherwise, for the first [TIMESTAMP](https://dev.mysql.com/doc/refman/8.4/en/datetime.html) column in a table, the default value is the current date and time. See [Section 13.2, “Date and Time Data Types”](https://dev.mysql.com/doc/refman/8.4/en/date-and-time-types.html).
> - For string types other than [ENUM](https://dev.mysql.com/doc/refman/8.4/en/enum.html), the default value is the empty string. For [ENUM](https://dev.mysql.com/doc/refman/8.4/en/enum.html), the default is the first enumeration value.

This behavior doesn't affect table creation, only writing to it (so it can be session-specific).

WPDB [disables both of these modes](https://github.com/WordPress/wordpress-develop/blob/24a2eacf7d69a9ae7ac0e7ac79eeacdd94777296/src/wp-includes/class-wpdb.php#L645), so for full WPDB compatibility, we need to support that.

See also [the old driver](https://github.com/Automattic/sqlite-database-integration/blob/5dfd5fa15417a903b1337f0a0293d461f3c7d407/wp-includes/sqlite/class-wp-sqlite-translator.php#L1199).

### PR DESCRIPTION
**Pull request by JanJakes**
### Summary
This PR implements the emulation of MySQL no-strict mode (disabled `STRICT_TRANS_TABLES`/`STRICT_ALL_TABLES`) in SQLite, and its modification and retrieval using `SET`/`SELECT` queries.

The non-strict mode is a requirement for WPDB, but in other environments (phpMyAdmin, etc.), it's likely to be left to the MySQL default, which is `STRICT_TRANS_TABLES` (strict mode for `InnoDB` tables).

Closes https://github.com/Automattic/sqlite-database-integration/issues/17.

#### Strict vs. non-strict mode
The implementation was done in the PHP SQLite driver code, and from a high-level perspective, it does the following:

1. In non-strict mode, `INSERT INTO table (optionally some columns) <select-or-values>` is rewritten to `INSERT INTO table (all table columns) SELECT <non-strict-mode-adjusted-values> FROM (<select-or-values>)`.
2. In non-strict mode, `UPDATE table SET column = <value>` is rewritten to `UPDATE table SET column = COALESCE(<value>, <implicit-default>)`, when the column is non-nullable.

#### Details
When zooming into the details, the above-described logic is quite involved and handles things like:
- We need to read the column metadata to determine the implicit defaults.
- An `INSERT` statements may list no fields, or any fields in any order.
- With `INSERT INTO ... SELECT ...` we don't know what fields the `SELECT` returns, and we need to figure that out.
- With `UPDATE` statements, a `NULL` may set a `NULL` value or an implicit default, depending on the column definition.
- All of the above should work for temporary tables as well.

#### SET/SELECT SQL mode
The PR also implements the following statements:
- `SET` for session `sql_mode` value.
- `SELECT` for session `sql_mode` value.

The `SET` statement is a surprisingly complex one, with various syntax flavors and multi-command support. Statements like `SET @var = '...', SESSION sql_mode = '...', @@GLOBAL.time_zone = '...', @@debug = '...', ...` are valid, including strange semantics, such as carrying the variable type keywords (`SESSION`, etc.) through to the subsequent definitions in the same statement.

#### WPDB
This PR also handles `$wpdb->set_sql_mode()` for the SQLite driver, as well as initializing the SQL mode for each connection.

#### Strict/non-strict behavior
Here's a summary of the implemented strict vs. non-strict mode behavior:

```
When STRICT_TRANS_TABLES or STRICT_ALL_TABLES is enabled:
  1. NULL + NO DEFAULT:     No value saves NULL, NULL saves NULL, DEFAULT saves NULL.
  2. NULL + DEFAULT:        No value saves DEFAULT, NULL saves NULL, DEFAULT saves DEFAULT.
  3. NOT NULL + NO DEFAULT: No value is rejected, NULL is rejected, DEFAULT is rejected.
  4. NOT NULL + DEFAULT:    No value saves DEFAULT, NULL is rejected, DEFAULT saves DEFAULT.

When STRICT_TRANS_TABLES and STRICT_ALL_TABLES are disabled:
  1. NULL + NO DEFAULT:     No value saves NULL, NULL saves NULL, DEFAULT saves NULL.
  2. NULL + DEFAULT:        No value saves DEFAULT, NULL saves NULL, DEFAULT saves DEFAULT.
  3. NOT NULL + NO DEFAULT: No value saves IMPLICIT DEFAULT.
                            NULL is rejected on INSERT, but saves IMPLICIT DEFAULT on UPDATE.
                            DEFAULT saves IMPLICIT DEFAULT.
  4. NOT NULL + DEFAULT:    No value saves DEFAULT.
                            NULL is rejected on INSERT, but saves IMPLICIT DEFAULT on UPDATE.
                            DEFAULT saves DEFAULT.
```
---

### Other paths considered and attempted
Initially, I started the implementation with the presumption that handling the strict vs. non-strict mode correctly and dynamically on the PHP driver side would be very hard, and I tried to implement this using other approaches at first.

#### 1. `DEFAULT` and `CHECK` expressions
SQLite supports expressions in `DEFAULT` definitions for columns, as well as in `CHECK` constraints. The natural first direction would be to make a default conditional to emulate the non-strict mode, or, conversely, make a constraint check conditional to emulate the strict mode.

It seems elegant in theory, but it doesn't work because both `DEFAULT` and `CHECK` expressions need to be "constant", which means they can't reference any other columns or tables, and they can only use [deterministic functions](https://www.sqlite.org/deterministic.html), that is, functions that always return the same value during a single session (except for date/time functions that are a special case).

This means using these expressions to apply strict/non-strict mode conditionally is not possible (and it's actually not possible to use non-deterministic user-defined functions in other cases either).

#### 2. Triggers
The idea here was to use before or after `INSERT` and `UPDATE` triggers to modify the new column values to emulate the MySQL implicit defaults. For each table, a specifically tailored trigger could be composed at the time of the table creation or modification.

This turned out to be problematic, and actually nearly impossible without additional complex or dirty hacks because:
1. SQLite doesn't support modifying the `NEW` row values in triggers. We can overcome this by using `AFTER` triggers and updating the values.
2. It may be tricky to keep the trigger up-to-date across table modifications, renames, etc., although definitely solvable.
3. There is no way to distinguish an explicit `NULL` value from an omitted value from `INSERT` within a view. This is a dealbreaker, although solvable with views (see below).
4. There is no way of passing any runtime per-session information into the trigger whatsoever, which means there is no way to tell the trigger what's the current SQL mode. There are no user variables in SQLite, temporary tables can't be referenced from non-temporary triggers, non-deterministic user-defined functions are not allowed in triggers, and user-modifiable pragmas (`application_id`) are not session-specific. Using a real table for this seemed to become a bit too hacky to me. However, this can be overcome with views (see below).

The prototype can be found in the following draft PR: https://github.com/Automattic/sqlite-database-integration/pull/30

#### 3. Views & triggers
SQLite supports views, and even though they are not writable, we can use `INSTEAD OF` triggers to hijack the values from the `INSERT` or `UPDATE` query, and perform custom logic instead. This approach is very similar to the previous one with triggers only, and it solves its main pain points:

1. While we can't pass any runtime information into the triggers, we can choose at runtime whether we'll execute the `INSERT` or `UPDATE` against the original table or against a view that implements "non-strict" triggers.
2. Distinguishing an explicit `NULL` value from an omitted one can be done with a hack. The view can define an extra column with a default value, and we can then use that column to sneak in a string of column names that were explicitly used in the insert statement. It's not a nice solution, but it works.

This approach seemed to work, until I executed the full test case only to realize that `SQLITE_ERROR: sqlite3 result code 1: cannot UPSERT a view`. So that was it for views.

The prototype can be found in the following draft PR: https://github.com/Automattic/sqlite-database-integration/pull/31

### CODE REVIEW

**Comment by adamziel** [comment]
The approach taken here is a good compromise. I'm sorry none of the other paths didn't work. One thing that bothers me is the proliferation of ways to insert and update data in MySQL. Let's make sure all our bases are covered – here's a few more query types I can think of:

* [REPLACE](https://dev.mysql.com/doc/refman/8.4/en/replace.html)
* LOAD DATA and LOAD XML – we can just bale out on these but I want to point them out
* CREATE TABLE AS SELECT
* [DO SELECT](https://dev.mysql.com/doc/refman/8.4/en/do.html)
* ...potentially more

We don't have to actually support all of these on day 1, but it would be useful to at least display a warning when running into an unsupported combination of operation + sql mode.

**Comment by adamziel** [comment]
> The SET statement is a surprisingly complex one, with various syntax flavors and multi-command support. Statements like SET @var = '...', SESSION sql_mode = '...', @@GLOBAL.time_zone = '...', @@debug = '...', ... are valid, including strange semantics, such as carrying the variable type keywords (SESSION, etc.) through to the subsequent definitions in the same statement.

Would this also support things like `SELECT (@last_id := id) FROM wp_posts`?

Also, there's at least a few scenarios where we could reasonably bale out, e.g. most hosts would likely not allow a SET that updates `mysqld-auto.cnf`.

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 1]
```diff
@@ -215,6 +215,74 @@ class WP_SQLite_Driver {
...
+	/**
+	 * A map of MySQL data types to implicit default values for non-strict mode.
+	 *
+	 * In MySQL, when STRICT_TRANS_TABLES and STRICT_ALL_TABLES modes are disabled,
+	 * columns get IMPLICIT DEFAULT values that are used under some circumstances.
+	 *
+	 * See:
+	 *   https://dev.mysql.com/doc/refman/8.4/en/data-type-defaults.html#data-type-defaults-implicit
+	 */
+	const DATA_TYPE_IMPLICIT_DEFAULT_MAP = array(
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php:227]: really good find

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 2]
```diff
@@ -1669,6 +1798,137 @@ private function execute_use_statement( WP_Parser_Node $node ): void {
...
+					|| 'setSystemVariable' === $part->rule_name
+				)
+			) {
+				array_shift( $definition ); // Remove the '='.
+				$value = array_shift( $definition );
+				$this->execute_set_system_variable_statement( $part, $value, $default_type );
+			}
+		}
+
+		// TODO: Support user variables (in-memory or a temporary table).
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php]: let's communicate lack of support with a warning or error to at least make the developer aware why their code breaks

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 3]
```diff
@@ -1669,6 +1798,137 @@ private function execute_use_statement( WP_Parser_Node $node ): void {
...
+		$value = substr( $value, 1, -1 );
+
+		if ( WP_MySQL_Lexer::SESSION_SYMBOL === $type ) {
+			if ( 'sql_mode' === $name ) {
+				$modes                  = explode( ',', strtoupper( $value ) );
+				$this->active_sql_modes = $modes;
+			}
+		}
+
+		// TODO: Handle GLOBAL, PERSIST, and PERSIST_ONLY types.
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php:1939]: Let's bale out with an error to make sure we don't give a false illusion of these queries actually working. It should also make it easier for us to spot any plugins relying on these semantics

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 4]
```diff
@@ -2592,6 +2877,203 @@ private function translate_show_like_or_where_condition( WP_Parser_Node $like_or
 		return '';
 	}
 
+	/**
+	 * Translate INSERT body, emulating MySQL implicit defaults in non-strict mode.
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php]: great comment :heart: it makes the intended purpose very clear 🚀  I want to highlighting that for everyone, cc @bgrgicak @brandonpayton @akirk @zaerl

Comment (adamziel) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php]: The only thing I'd add is the INSERT before the translation and the expected INSERT after the translation – same as in the PR description

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 5]
```diff
@@ -2592,6 +2877,203 @@ private function translate_show_like_or_where_condition( WP_Parser_Node $like_or
...
+			$stmt = $this->execute_sqlite_query(
+				'SELECT * FROM (' . $this->translate( $expr ) . ') LIMIT 1'
+			);
+			$stmt->execute();
+
+			for ( $i = 0; $i < $stmt->columnCount(); $i++ ) {
+				$select_list[] = $stmt->getColumnMeta( $i )['name'];
+			}
+		} else {
+			// When inserting from a VALUES list, SQLite uses "columnN" naming.
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php:2986]: TIL

**Review by adamziel — APPROVED** [review]
I've left a few nitpicks around being very strict with errors in cases we don't support. The PR is solid, the approach well-researched, and the reasoning clear. It's always a pleasure to review these SQL PRs, thank you for your great work @JanJakes !

**Comment by JanJakes** [comment]
@adamziel Thanks!

> Would this also support things like SELECT (@last_id := id) FROM wp_posts?

Probably not, [these seem to be part of the expression grammar](https://github.com/Automattic/sqlite-database-integration/blob/c9b443b5bb918dd828a0dd1c322697bfd92272bb/grammar-tools/MySQLParser.g4#L2973), and not part of the `SET` statement.

> Also, there's at least a few scenarios where we could reasonably bale out, e.g. most hosts would likely not allow a SET that updates mysqld-auto.cnf.

True, we'll need to go through a list of the variables at some point.

**Comment by JanJakes** [comment]
@adamziel

Great point to check whether all ways of data manipulation are covered or disabled!

> Let's make sure all our bases are covered – here's a few more query types I can think of:

> [REPLACE](https://dev.mysql.com/doc/refman/8.4/en/replace.html)
> LOAD DATA and LOAD XML – we can just bale out on these but I want to point them out
> CREATE TABLE AS SELECT
> [DO SELECT](https://dev.mysql.com/doc/refman/8.4/en/do.html)
> ...potentially more

`REPLACE` actually works, I forgot to reflect that in the test, adding a test now ([commit](https://github.com/Automattic/sqlite-database-integration/pull/29/commits/d39df538d3aa042f8b8b922199dc4d920b70dd9f)).

`LOAD` is not supported at all at the moment, I think that will just fail.

`CREATE TABLE AS SELECT` is explicitly disabled for now, as we don't support creating information schema data that way.

Can a `DO` statement insert any data? I don't know if there is any other way to insert data. Also consulting ChatGPT, and it doesn't seem to know of any other ways.

---

This made me think if there are any other variants for the `UPDATE` statements.

I found one I didn't consider before — `INSERT ... ON DUPLICATE KEY UPDATE`. So I first tried it in MySQL, and to my surprise, MySQL doesn't consider the non-strict mode in the `ON DUPLICATE KEY UDPATE` clause:

```sql
SET SESSION sql_mode = '';

CREATE TABLE t1 (id INT PRIMARY KEY, name TEXT NOT NULL);
INSERT INTO t1 (id) VALUES (1);

-- this works (implicit default)
UPDATE t1 SET name = NULL;

-- this fails with "ERROR 1048 (23000) at line 6: Column 'name' cannot be null"
INSERT INTO t1 (id) VALUES (1) ON DUPLICATE KEY UPDATE name = NULL;
```

So that's great, since it already behaves that way, and I only [added a test](https://github.com/Automattic/sqlite-database-integration/pull/29/commits/079166da9e6600f366a95d7e0834b7e9af1e4a8b).

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php (hunk 4 above)
Comment (JanJakes) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php]: 👍 Added the input/output in https://github.com/Automattic/sqlite-database-integration/pull/29/commits/f922251617388a2d7626cfed6e3235a056478395.

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php (hunk 2 above)
Comment (JanJakes) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php]: 👍 Added in https://github.com/Automattic/sqlite-database-integration/pull/29/commits/d6f6b6d93c94d0e181a89677b75c8a2284c790aa.

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php (hunk 3 above)
Comment (JanJakes) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php:1939]: 👍 Resolved in https://github.com/Automattic/sqlite-database-integration/pull/29/commits/d6f6b6d93c94d0e181a89677b75c8a2284c790aa.

**Comment by adamziel** [comment]
> I first tried it in MySQL, and to my surprise, MySQL doesn't consider the non-strict mode in the ON DUPLICATE KEY UDPATE clause

Oh MySQL 🙈

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 6]
```diff
@@ -1265,7 +1386,15 @@ private function execute_truncate_table_statement( WP_Parser_Node $node ): void
 		$quoted_table_name = $this->quote_sqlite_identifier( $table_name );
 
 		$this->execute_sqlite_query( "DELETE FROM $quoted_table_name" );
-		$this->execute_sqlite_query( 'DELETE FROM sqlite_sequence WHERE name = ?', array( $table_name ) );
+		try {
+			$this->execute_sqlite_query( 'DELETE FROM sqlite_sequence WHERE name = ?', array( $table_name ) );
+		} catch ( PDOException $e ) {
+			if ( str_contains( $e->getMessage(), 'no such table' ) ) {
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php:1392]: Would checking the error code be more reliable here?

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 7]
```diff
@@ -2592,6 +2887,215 @@ private function translate_show_like_or_where_condition( WP_Parser_Node $like_or
...
 
+	/**
+	 * Translate INSERT or REPLACE statement body to SQLite, while emulating
+	 * the behavior of MySQL implicit default values in non-strict mode.
+	 *
+	 * Rewrites a statement body in the following form:
+	 *   INSERT INTO table (optionally some columns) <select-or-values>
+	 * To a statement body with the following structure:
+	 *   INSERT INTO table (all table columns)
+	 *   SELECT <non-strict-mode-adjusted-values> FROM (<select-or-values>) WHERE true
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php:2898]: :heart:

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 8]
```diff
@@ -2592,6 +2887,215 @@ private function translate_show_like_or_where_condition( WP_Parser_Node $like_or
...
+			// When inserting from a VALUES list, SQLite uses "columnN" naming.
+			foreach ( array_keys( $insert_list ) as $position ) {
+				$select_list[] = 'column' . ( $position + 1 );
+			}
+		}
+
+		// 4. Compose a new INSERT field list with all columns from the table.
+		$fragment = '(';
+		foreach ( $columns as $i => $column ) {
+			$fragment .= $i > 0 ? ', ' : '';
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php:2995]: Nothing actionable for this PR but man, I wish we had a more convenient way of building these SQL queries – both for us here and for WordPress core. cc @dmsnell – we've discussed this recently

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 9]
```diff
@@ -2592,6 +2887,215 @@ private function translate_show_like_or_where_condition( WP_Parser_Node $like_or
...
+				// need to use the DEFAULT value or the IMPLICIT DEFAULT value.
+				$is_auto_inc = str_contains( $column['EXTRA'], 'auto_increment' );
+				$is_nullable = 'YES' === $column['IS_NULLABLE'];
+				$default     = $column['COLUMN_DEFAULT'];
+				if ( null === $default && ! $is_nullable && ! $is_auto_inc ) {
+					$default = self::DATA_TYPE_IMPLICIT_DEFAULT_MAP[ $column['DATA_TYPE'] ] ?? null;
+				}
+				$fragment .= null === $default ? 'NULL' : $this->pdo->quote( $default );
+			} else {
+				// When a colum value is included, we can use it without change.
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php]:
```suggestion
				// When a column value is included, we can use it without change.
```

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php [hunk 10]
```diff
@@ -2592,6 +2887,215 @@ private function translate_show_like_or_where_condition( WP_Parser_Node $like_or
...
+				$position  = array_search( $column['COLUMN_NAME'], $insert_list, true );
+				$fragment .= $this->quote_sqlite_identifier( $select_list[ $position ] );
+			}
+		}
+
+		// 6. Wrap the original insert VALUES or SELECT expression in a FROM clause.
+		$values    = 'insertFromConstructor' === $node->rule_name
+			? $node->get_first_child_node( 'insertValues' )
+			: $node->get_first_child_node( 'queryExpressionOrParens' );
+		$fragment .= ' FROM (' . $this->translate( $values ) . ') WHERE true';
```
Comment (adamziel) [inline wp-includes/sqlite-ast/class-wp-sqlite-driver.php:3026]: Why do we need WHERE true? Is this stitched with `AND ...` later on? Also, TIL we can do a subquery like that without giving it an alias.

**Review by adamziel — APPROVED** [review]

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php (hunk 10 above)
Comment (JanJakes) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php:3026]: @adamziel It was failing without that, and [then I found it documented](https://www.sqlite.org/lang_insert.html):

Screenshot 2025-03-25 at 15 47 05

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php (hunk 6 above)
Comment (JanJakes) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php:1392]: @adamziel For some reason, I'm not getting the correct SQLSTATE back: `SQLSTATE[HY000]: General error: 1 no such table: sqlite_sequence`

It may be something about the PDO driver in SQLite. The correct SQLSTATE should be `42S02`.

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php (hunk 8 above)
Comment (JanJakes) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php:2995]: @adamziel Just yesterday, I was trying to brainstorm with ChatGPT about a lightweight but powerful SQL builder API in PHP. PHP is quite limited for these types of APIs, especially with typing (we'll never be able to do anything like [Drizzle ORM](https://orm.drizzle.team/)), but it would definitely be great to have something like that for WordPress.

File: wp-includes/sqlite-ast/class-wp-sqlite-driver.php (hunk 10 above)
Comment (adamziel) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php:3026]: TIL. Let's leave a comment with a link inline – it's the kind of thing that seems too easy to remove when not careful

Comment (JanJakes) [reply wp-includes/sqlite-ast/class-wp-sqlite-driver.php:3026]: @adamziel 👍  Added in https://github.com/Automattic/sqlite-database-integration/commit/3faa5533f5ad1b9299430d54a263c3383cce011d.
